### PR TITLE
Corrects for change in numPLsDefined keyword

### PR DESCRIPTION
**Pull request by bhourahine**

### CODE REVIEW

**Review by vanderhe — APPROVED** [review]
Despite my limited knowledge of the transport functionality, I think it is save to merge and as far as I can see accounts for the changes of [#263](https://github.com/dftbplus/dftbplus/pull/263), merged quite a while ago.

**Comment by bhourahine** [comment]
@vanderhe There is also an equivalent documentation fix over in the [code repo](https://github.com/dftbplus/dftbplus/pull/1288), if you get 5 minutes could you have a quick look at that as well? Thanks.

**Comment by vanderhe** [comment]
> @vanderhe There is also an equivalent documentation fix over in the [code repo](https://github.com/dftbplus/dftbplus/pull/1288), if you get 5 minutes could you have a quick look at that as well? Thanks.

Sure, will have a look at it now.

**Comment by pecchia** [comment]
I think this is fine. I am checking if the fix on zerobased Is still working. I am not sure what are all the undocumented features. This is a fundamental tool to make transport calc easier

**Pull request merged**
