### PR TITLE
Update maximum absolute gradient element keyword

### PR DESCRIPTION
**Pull request by vanderhe**
Update maximum absolute gradient element keyword from `GradAMax` to `GradElem`.

### CODE REVIEW

**Comment by vanderhe** [comment]
@bhourahine It seems that one can add any garbage to the `Convergence {}` block without the parser complaining about it. The entry also propagates into `dftb_pin.hsd`. That shouldn't be allowed right?

**Comment by bhourahine** [comment]
> @bhourahine It seems that one can add any garbage to the `Convergence {}` block without the parser complaining about it. The entry also propagates into `dftb_pin.hsd`. That shouldn't be allowed right?

@vanderhe agreed.

**Comment by bhourahine** [comment]
@vanderhe The issue is due to use of getChildValue() instead of getChild() in the calling routine, but as to why the getChildValue case is marking ignored nodes as parsed...

**Comment by bhourahine** [comment]
@vanderhe PR [1384](https://github.com/dftbplus/dftbplus/pull/1384) in the main repository blocks the specific problem.

**Pull request merged**
